name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build with dotnet
      run: |
        cd GameLogic
        dotnet build --configuration Release
        cd ../GameLogicTests
        dotnet build --configuration Release
        cd ../SkyjoConsoleInterface
        dotnet build --configuration Release
        cd ../
    - name: Test with dotnet
      run: |
        cd GameLogicTests
        dotnet test  --configuration Release
